; university_outside.asm - university exterior, 80 x 12 tiles (see tiles.asm)
; Generated from the mockup: only tiles that exist today; sky, clouds, roof rail,
; grass, sidewalk, road and entrance pillars are EMP until their chars/DLIs exist.
; Each map row = 2 lines of 40 tiles (atasm limits line length).

university_outside
    ; row 0
    .BYTE EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP
    .BYTE EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP
    ; row 1
    .BYTE EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP
    .BYTE EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP
    ; row 2
    .BYTE EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP
    .BYTE EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP
    ; row 3
    .BYTE EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP
    .BYTE EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP
    ; row 4
    .BYTE EMP,EMP,EMP,BRA,WNL,WNR,BRB,WNL,WNR,BRB,WNL,WNR,BRA,WNL,WNR,BRA,WNL,WNR,BRC,WNL,WNR,BRB,WNL,WNR,WNL,WNR,WNL,WNR,WNL,WNR,WNL,WNR,BRA,WNL,WNR,BRB,WNL,WNR,BRB,WNL
    .BYTE WNR,BRA,WNL,WNR,BRA,WNL,WNR,BRC,WNL,WNR,BRB,WNL,WNR,BRA,WNL,WNR,BRB,WNL,WNR,BRB,WNL,WNR,BRA,WNL,WNR,BRA,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP
    ; row 5
    .BYTE EMP,EMP,EMP,BRA,WNL,WNR,BRB,WNL,WNR,BRB,WNL,WNR,BRA,WNL,WNR,BRA,WNL,WNR,BRC,WNL,WNR,BRB,WNL,WNR,WNL,WNR,WNL,WNR,WNL,WNR,WNL,WNR,BRA,WNL,WNR,BRB,WNL,WNR,BRB,WNL
    .BYTE WNR,BRA,WNL,WNR,BRA,WNL,WNR,BRC,WNL,WNR,BRB,WNL,WNR,BRA,WNL,WNR,BRB,WNL,WNR,BRB,WNL,WNR,BRA,WNL,WNR,BRA,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP
    ; row 6
    .BYTE EMP,EMP,EMP,BRA,WNL,WNR,BRB,WNL,WNR,BRB,WNL,WNR,BRA,WNL,WNR,BRA,WNL,WNR,BRC,WNL,WNR,BRB,WNL,WNR,WNL,WNR,WNL,WNR,WNL,WNR,WNL,WNR,BRA,WNL,WNR,BRB,WNL,WNR,BRB,WNL
    .BYTE WNR,BRA,WNL,WNR,BRA,WNL,WNR,BRC,WNL,WNR,BRB,WNL,WNR,BRA,WNL,WNR,BRB,WNL,WNR,BRB,WNL,WNR,BRA,WNL,WNR,BRA,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP
    ; row 7
    .BYTE EMP,EMP,EMP,BRA,WNL,WNR,BRB,WNL,WNR,BRB,WNL,WNR,BRA,WNL,WNR,BRA,WNL,WNR,BRC,WNL,WNR,BRB,WNL,WNR,WNL,WNR,WNL,WNR,WNL,WNR,WNL,WNR,BRA,WNL,WNR,BRB,WNL,WNR,BRB,WNL
    .BYTE WNR,BRA,WNL,WNR,BRA,WNL,WNR,BRC,WNL,WNR,BRB,WNL,WNR,BRA,WNL,WNR,BRB,WNL,WNR,BRB,WNL,WNR,BRA,WNL,WNR,BRA,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP
    ; row 8
    .BYTE EMP,EMP,EMP,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,EMP,FLW,EMP,FLW,FLW,EMP,FLW,EMP,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW
    .BYTE FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,FLW,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP
    ; row 9
    .BYTE EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP
    .BYTE EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP
    ; row 10
    .BYTE EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP
    .BYTE EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP
    ; row 11
    .BYTE EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP
    .BYTE EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP,EMP
